"""empty message

Revision ID: 957ffd8720d8
Revises: ff89f3244cc9
Create Date: 2024-07-19 08:22:52.947896

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "957ffd8720d8"
down_revision: Union[str, None] = "ff89f3244cc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("create_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.create_table(
        "chat_members",
        sa.Column("chat_member_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("date_when_added", sa.Date(), nullable=False),
        sa.Column("is_creator", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.chat_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("chat_member_id"),
    )
    op.create_table(
        "messages",
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("chat_member_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("time_sent", sa.Date(), nullable=False),
        sa.Column("reply_to", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_member_id"], ["chat_members.chat_member_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["reply_to"],
            ["messages.message_id"],
        ),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_table(
        "message_images",
        sa.Column("message_image_id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("image_path", sa.String(length=300), nullable=False),
        sa.PrimaryKeyConstraint("message_image_id"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.message_id"], ondelete="CASCADE"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    op.drop_table("chat_members")
    op.drop_table("message_images")
    op.drop_table("chats")
    # ### end Alembic commands ###
